Bookshelf/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bookshelf.Models
{
    public class Comment
    {
        public Comment()
        {
            AddedDate = DateTime.Now;
        }

        [Required]
        public int Id { get; private set; }
        [Required]
        public int BookId { get; private set; }
        [Required]
        public string UserId { get; private set; }
        [Required]
        public string Text { get; private set; }
        [Required]
        public DateTime AddedDate { get; private set; }
        public virtual Book Book { get; private set; }
        public virtual ApplicationUser User { get; private set; }

        public static Comment Create(int bookId, string userId)
        {
            return new Comment { BookId = bookId, UserId = userId };
        }
    }
}

Bookshelf/Models/ViewModels/CommentsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bookshelf.Models.ViewModels
{
    public class AddCommentViewModel
    {
        [Required]
        public string GoogleBookId { get; set; }
        [Required]
        public string Text { get; set; }
    }

    public class CommentInfoViewModel
    {
        public int Id { get; private set; }
        public int BookId { get; private set; }
        public string Text { get; private set; }
        public DateTime AddedDate { get; private set; }
        public UserCommentViewModel User { get; private set; }
    }
}

Bookshelf/Controllers/BooksController.cs
using AutoMapper;
using Bookshelf.BookApiConnection;
using Bookshelf.Constants;
using Bookshelf.Models;
using Bookshelf.Models.ViewModels;
using Bookshelf.Repository;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Bookshelf.Controllers
{
    [RoutePrefix("books")]
    public class BooksController : Controller
    {
        private readonly IApiConnector _apiConnector;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public BooksController(IApiConnector apiConnector, IUnitOfWork unitOfWork, IMapper mapper)
        {
            _apiConnector = apiConnector;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [Route("add-book-to-read")]
        // GET: Books
        public ActionResult AddBookToRead()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> GetBooksByPhrase(string phrase, int startIndex, int size = 30)
        {
            string url = ApiUrls.SEARCH_BOOK_BY_PHRASE + phrase + "&maxResults=" + size + "&startIndex=" + startIndex;
            BooksVolume items = null;

            Uri uri = new Uri(url);
            try
            {
                HttpResponseMessage response = await _apiConnector.Get(uri);
                string message = await response.Content.ReadAsStringAsync();
                items = JsonConvert.DeserializeObject<BooksVolume>(message);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return PartialView("SearchBookResultPartial", items);
        }

        [Route("book-details/{id}")]
        [Authorize]
        public async Task<ActionResult> BookDetails(string id)
        {
            Uri uri = new Uri(ApiUrls.SEARCH_BOOK_BY_ID + id);
            Volume book = null;
            try
            {
                HttpResponseMessage response = await _apiConnector.Get(uri);
                string content = await response.Content.ReadAsStringAsync();
                book = JsonConvert.DeserializeObject<Volume>(content);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return View(book);
        }


        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddBookshelf(AddBookViewModel model)
        {
            Book book = Book.Create(model);

            bool isShelfInDatabase = await _unitOfWork.BookshelfRepository.IsInDatabase(User.Identity.GetUserId(), model.GoogleId);
            if (isShelfInDatabase)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Bookshelf exist in database!");
            }

            try
            {
                Book resultBook = await _unitOfWork.BookRepository.FindOrAddAsync(book);
                Shelf shelf = new Shelf(resultBook.Id, User.Identity.GetUserId());
                _unitOfWork.BookshelfRepository.Add(shelf);
                await _unitOfWork.CompleteAsync();
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return Json("Added sucessfully!");
        }

        [Authorize]
        public async Task<ActionResult> IsBookshelfInDatabase(string googleBookId)
        {
            bool isInDatabase = false;
            try
            {
                isInDatabase = await _unitOfWork.BookshelfRepository.IsInDatabase(User.Identity.GetUserId(), googleBookId);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            IsAddedToBookshelf added = new IsAddedToBookshelf { IsAdded = isInDatabase };

            return Json(added, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [Route("your-books")]
        public ActionResult UserBooks()
        {
            return View();
        }

        [Authorize]
        public async Task<ActionResult> GetUserBookshelf()
        {
            try
            {
                var shelfs = await _unitOfWork.BookshelfRepository.GetAllByUserId(User.Identity.GetUserId());
                var data = _mapper.Map<List<ShelfViewModel>>(shelfs);
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> ChangeTheReadingOfTheBook(int shelfId)
        {
            var result = await _unitOfWork.BookshelfRepository.ChangeTheReadingStatusOfTheBook(shelfId);
            await _unitOfWork.CompleteAsync();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> DeleteShelf(int id)
        {
            try
            {
                await _unitOfWork.BookshelfRepository.Delete(id);
                await _unitOfWork.CompleteAsync();
            }
            catch (Exception e)
            {
                return Json("error");
            }
            return Json("success");
        }

       
    }
}

Bookshelf/Controllers/CommentsController.cs
using AutoMapper;
using Bookshelf.Models;
using Bookshelf.Models.ViewModels;
using Bookshelf.Repository;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Bookshelf.Controllers
{
    public class CommentsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public CommentsController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<ActionResult> GetCommentsForBook(string bookId)
        {
            List<Comment> comments = null;
            List<CommentInfoViewModel> model = new List<CommentInfoViewModel>();
            try
            {
                comments = await _unitOfWork.CommentRepository.GetByGoogleBookId(bookId);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            model = _mapper.Map<List<CommentInfoViewModel>>(comments);
            return PartialView("_Comments", model);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Add(AddCommentViewModel model)
        {
            Comment comment = null;
            Comment result = null;

            try
            {
                var book = await _unitOfWork.BookRepository.FindByGoogleIdAsync(model.GoogleBookId);
                comment = Comment.Create(book.Id, User.Identity.GetUserId());
                comment = _mapper.Map(model, comment);
                result = _unitOfWork.CommentRepository.Add(comment);
                await _unitOfWork.CompleteAsync();
            }
            catch (Exception e)
            {
                return Json("error");
            }
            CommentInfoViewModel returnModel = _mapper.Map<CommentInfoViewModel>(result);
            return Json(returnModel);
        }
    }
}

Bookshelf/Controllers/QuotationController.cs
using Bookshelf.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bookshelf.Controllers
{
    public class QuotationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public QuotationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Route("your-quotations")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Bookshelf/Views/Shared/_Comments.cshtml
@model IEnumerable<Bookshelf.Models.ViewModels.CommentInfoViewModel>
<div class="row">
    <div class="comments-section">
        <div class="clearfix"></div>

        <div class="comment-success" style="display:none;">
            <p>Comment was successfully added!</p>
        </div>

        <div class="loader-section"></div>


        @foreach (var comment in Model)
        {
            <div class="col-md-12">
                <div class="comment-block">
                    <div class="panel panel-default">
                        <div class="comment-date">@comment.AddedDate</div>
                        <p class="comment-text">
                            @comment.Text
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@*<div class="comments">
        <div class="comment-wrap">
            <div class="comment-block">
                <textarea name="" id="" cols="30" rows="3" placeholder="Add comment..."></textarea>
            </div>
        </div>
        <button class="btn btn-default btn-sm pull-right" id="submit-form-button">ADD</button>
        <div class="comment-wrap">
            <div class="comment-block">
                <p class="comment-text">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto temporibus iste nostrum dolorem natus recusandae incidunt voluptatum. Eligendi voluptatum ducimus architecto tempore, quaerat explicabo veniam fuga corporis totam reprehenderit quasi
                    sapiente modi tempora at perspiciatis mollitia, dolores voluptate. Cumque, corrupti?
                </p>
                <div class="bottom-comment">
                    <div class="comment-date">Aug 24, 2014  2:35 PM</div>
                </div>
            </div>
        </div>
        <div class="comment-wrap">

            <div class="comment-block">
                <p class="comment-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto temporibus iste nostrum dolorem natus recusandae incidunt voluptatum. Eligendi voluptatum ducimus architecto tempore, quaerat explicabo veniam fuga corporis totam.</p>
                <div class="bottom-comment">
                    <div class="comment-date">Aug 23, 2014  10:32 AM</div>
                </div>
            </div>
        </div>
    </div>*@

Bookshelf/Views/Shared/_HeaderImage.cshtml
<div class="container">
    <div class="row">
        <img src="~/Content/Images/bookshelf.jpg" class="img-responsive" />
    </div>
</div>

Bookshelf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon icon" type="image/x-icon" href="~/Content/Images/Favicons/favicon.ico" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("AddDatatablesToHead", required: false)
    @RenderSection("BookDetailsCustomStyle", required: false)


</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookShelf", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                    <li>@Html.ActionLink("ABOUT", "About", "Home")</li>
                    <li>@Html.ActionLink("CONTACT", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="false" aria-expanded="false">MANAGE BOOKSHELF <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Your bookshelf", "UserBooks", "Books")</li>
                                <li>@Html.ActionLink("Add a book", "AddBookToRead", "Books")</li>
                                @*<li>@Html.ActionLink("Rate a book", "", "")</li>*@
                                <li>@Html.ActionLink("Your quotations", "Index", "Quotation")</li>
                                    @*<li>@Html.ActionLink("Proposed books", "", "")</li>*@
                            </ul>
                        </li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <p class="text-muted">&copy; @DateTime.Now.Year - Bookshelf Application</p>
        </div>
    </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom-for-all-page")


    @RenderSection("scripts", required: false)
</body>
</html>